# Generated by Django 4.1.1 on 2022-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=30)),
                ('employe_id', models.CharField(max_length=6, unique=True)),
                ('department', models.CharField(max_length=20)),
                ('salary', models.IntegerField(max_length=10)),
                ('manager', models.CharField(max_length=30)),
                ('task', models.CharField(max_length=50)),
                ('task_in_progress', models.CharField(max_length=4)),
                ('id_proof', models.FileField(upload_to=None)),
            ],
        ),
    ]
